#!/bin/bash

declare -A list=()
while read file; do
	item="$( basename "$file" )"
	item="${item%.*}"
	[ "$item" = shdoc ] && continue
	echo file=$file item=$item
	./shdoc/shdoc "$file" >REFERENCE-$item.md
	list["$item"]="$file"
done < <( find . -type f | grep -Ev '/\.git|/shdoc/|\.md$|\.swp|/'"$(basename $0)$" | xargs -n 1 grep -l '# @' 2>/dev/null )
declare -p list

cat >REFERENCE.md <<EOD
# Reference
**Library Files**
$(
for item in ${!list[@]}; do
	echo "* [${list["$item"]#./}](REFERENCE-$item.md)"
done
)
EOD
